import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header/Header';
import { Quicksand } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

const mainFont = Quicksand({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'EatyList',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'icon',
      type: 'image/x-icon',
      url: '/favicon.ico',
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={mainFont.className} style={{ fontSize: '1.2rem' }}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
